=== api-evangelist/weatherbit/json-schema/weatherbit-forecast-hour-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/weatherbit/refs/heads/main/json-schema/weatherbit-forecast-hour-schema.json",
  "title": "ForecastHour",
  "description": "ForecastHour schema from Weatherbit API",
  "type": "object",
  "properties": {
    "ts": {
      "type": "number",
      "description": "Unix Timestamp",
      "example": 1551718800
    },
    "timestamp_local": {
      "type": "string",
      "description": "Timestamp in local time",
      "example": "2019-03-04 12:00:00"
    },
    "timestamp_utc": {
      "type": "string",
      "description": "Timestamp UTC",
      "example": "2019-03-04 17:00:00"
    },
    "datetime": {
      "type": "string",
      "description": "Date in format \"YYYY-MM-DD:HH\". All datetime is in (UTC)",
      "example": "2019-03-04:17"
    },
    "snow": {
      "type": "number",
      "description": "Accumulated snowfall since last forecast point - Default (mm)",
      "example": 10.45
    },
    "precip": {
      "type": "number",
      "description": "Accumulated precipitation since last forecast point. Default (mm)",
      "example": 1.1
    },
    "temp": {
      "type": "number",
      "description": "Temperature - Default (C)",
      "example": -1.5
    },
    "dewpt": {
      "type": "number",
      "description": "Dewpoint - Default (C)",
      "example": -4.0
    },
    "app_temp": {
      "type": "number",
      "description": "Apparent Temperature - Default (C)",
      "example": 4.5
    },
    "rh": {
      "type": "integer",
      "description": "Relative Humidity as a percentage (%)",
      "example": 95
    },
    "clouds": {
      "type": "integer",
      "description": "Cloud cover as a percentage (%)",
      "example": 100
    },
    "weather": {
      "type": "object",
      "properties": {
        "icon": {
          "type": "string",
          "description": "Icon code for forecast image display",
          "example": "s02d"
        },
        "code": {
          "type": "integer",
          "description": "Weather Condition code",
          "example": 601
        },
        "description": {
          "type": "string",
          "description": "Weather Condition description",
          "example": "Snow"
        }
      }
    },
    "slp": {
      "type": "number",
      "description": "Mean Sea level pressure (mb)",
      "example": 1012.89
    },
    "pres": {
      "type": "number",
      "description": "Pressure (mb)",
      "example": 1005.0
    },
    "uv": {
      "type": "number",
      "description": "UV Index",
      "example": 6.5
    },
    "solar_rad": {
      "type": "number",
      "description": "Estimated solar radiation (W/m^2)",
      "example": 300.0
    },
    "ghi": {
      "type": "number",
      "description": "Global horizontal solar irradiance (W/m^2)",
      "example": 1000.0
    },
    "dhi": {
      "type": "number",
      "description": "Diffuse normal solar irradiance (W/m^2)",
      "example": 200.0
    },
    "dni": {
      "type": "number",
      "description": "Direct normal solar irradiance (W/m^2)",
      "example": 400.0
    },
    "vis": {
      "type": "number",
      "description": "Visibility - Default (KM)",
      "example": 1.0
    },
    "pod": {
      "type": "string",
      "description": "Part of day (d = day, n = night)",
      "example": "d"
    },
    "pop": {
      "type": "number",
      "description": "Chance of Precipitation as a percentage (%)",
      "example": 75.0
    },
    "wind_spd": {
      "type": "number",
      "description": "Wind Speed - Default (m/s)",
      "example": 13.85
    },
    "wind_gust_spd": {
      "type": "number",
      "description": "Wind Gust Speed - Default (m/s)",
      "example": 16.85
    },
    "wind_dir": {
      "type": "integer",
      "description": "Wind direction",
      "example": 105
    },
    "wind_cdir": {
      "type": "string",
      "description": "Cardinal wind direction",
      "example": "ENE"
    },
    "wind_cdir_full": {
      "type": "string",
      "description": "Cardinal wind direction (text)",
      "example": "East-North-East"
    }
  }
}

=== api-evangelist/weatherbit/examples/weatherbit-forecast-hour-example.json
{
  "ts": 1551718800,
  "timestamp_local": "2019-03-04 12:00:00",
  "timestamp_utc": "2019-03-04 17:00:00",
  "datetime": "2019-03-04:17",
  "snow": 10.45,
  "precip": 1.1,
  "temp": -1.5,
  "dewpt": -4.0,
  "app_temp": 4.5,
  "rh": 95,
  "clouds": 100,
  "weather": {
    "icon": "s02d",
    "code": 601,
    "description": "Snow"
  },
  "slp": 1012.89,
  "pres": 1005.0,
  "uv": 6.5,
  "solar_rad": 300.0,
  "ghi": 1000.0,
  "dhi": 200.0,
  "dni": 400.0,
  "vis": 1.0,
  "pod": "d",
  "pop": 75.0,
  "wind_spd": 13.85,
  "wind_gust_spd": 16.85,
  "wind_dir": 105,
  "wind_cdir": "ENE",
  "wind_cdir_full": "East-North-East"
}
