=== api-evangelist/weatherbit/json-schema/weatherbit-forecast-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/weatherbit/refs/heads/main/json-schema/weatherbit-forecast-schema.json",
  "title": "Forecast",
  "description": "Forecast schema from Weatherbit API",
  "type": "object",
  "properties": {
    "ts": {
      "type": "number",
      "description": "Unix Timestamp",
      "example": 1551718800
    },
    "timestamp_local": {
      "type": "string",
      "description": "Timestamp in local time",
      "example": "2019-03-04 12:00:00"
    },
    "timestamp_utc": {
      "type": "string",
      "description": "Timestamp UTC",
      "example": "2019-03-04 17:00:00"
    },
    "datetime": {
      "type": "string",
      "description": "Date in format \"YYYY-MM-DD:HH\". All datetime is in (UTC)",
      "example": "2019-03-04:17"
    },
    "snow": {
      "type": "number",
      "description": "Accumulated snowfall since last forecast point - default (mm)",
      "example": 10.45
    },
    "precip": {
      "type": "number",
      "description": "Accumulated precipitation since last forecast point - default (mm)",
      "example": 1.1
    },
    "temp": {
      "type": "number",
      "description": "Temperature (Average) - default (C)",
      "example": 1.0
    },
    "dewpt": {
      "type": "number",
      "description": "Dewpoint (Average) - default (C)",
      "example": 1.0
    },
    "max_temp": {
      "type": "number",
      "description": "Maximum daily Temperature - default (C)",
      "example": 1.5
    },
    "min_temp": {
      "type": "number",
      "description": "Minimum daily Temperature - default (C)",
      "example": -1.23
    },
    "app_max_temp": {
      "type": "number",
      "description": "Apparent Maximum daily Temperature - default (C)",
      "example": 4.0
    },
    "app_min_temp": {
      "type": "number",
      "description": "Apparent Minimum daily Temperature - default (C)",
      "example": -2.0
    },
    "rh": {
      "type": "integer",
      "description": "Relative Humidity as a percentage (%)",
      "example": 95
    },
    "clouds": {
      "type": "integer",
      "description": "Cloud cover as a percentage (%)",
      "example": 100
    },
    "weather": {
      "type": "object",
      "properties": {
        "icon": {
          "type": "string",
          "description": "Icon code for forecast image display",
          "example": "s02n"
        },
        "code": {
          "type": "integer",
          "description": "Weather Condition code",
          "example": 601
        },
        "description": {
          "type": "string",
          "description": "Weather Condition description",
          "example": "Snow"
        }
      }
    },
    "slp": {
      "type": "number",
      "description": "Mean Sea level pressure (mb)",
      "example": 1012.89
    },
    "pres": {
      "type": "number",
      "description": "Pressure (mb)",
      "example": 1005.0
    },
    "uv": {
      "type": "number",
      "description": "UV Index",
      "example": 6.5
    },
    "vis": {
      "type": "number",
      "description": "Average Visibility default (KM)",
      "example": 3.0
    },
    "pop": {
      "type": "number",
      "description": "Chance of Precipitation as a percentage (%)",
      "example": 75.0
    },
    "moon_phase": {
      "type": "number",
      "description": "Moon phase",
      "example": 0.87
    },
    "sunrise_ts": {
      "type": "integer",
      "description": "Sunrise unix timestamp",
      "example": 1530331260
    },
    "sunset_ts": {
      "type": "integer",
      "description": "Sunset unix timestamp",
      "example": 1530331260
    },
    "moonrise_ts": {
      "type": "integer",
      "description": "Moonrise unix timestamp",
      "example": 1530331260
    },
    "moonset_ts": {
      "type": "integer",
      "description": "Moonset unix timestamp",
      "example": 1530331260
    },
    "pod": {
      "type": "string",
      "description": "Part of the day (d = day, n = night)",
      "example": "n"
    },
    "wind_spd": {
      "type": "number",
      "description": "Wind Speed (default m/s)",
      "example": 13.85
    },
    "wind_dir": {
      "type": "integer",
      "description": "Wind direction",
      "example": 105
    },
    "wind_cdir": {
      "type": "string",
      "description": "Cardinal wind direction",
      "example": "ENE"
    },
    "wind_cdir_full": {
      "type": "string",
      "description": "Cardinal wind direction (text)",
      "example": "East-North-East"
    }
  }
}

=== api-evangelist/weatherbit/examples/weatherbit-forecast-example.json
{
  "ts": 1551718800,
  "timestamp_local": "2019-03-04 12:00:00",
  "timestamp_utc": "2019-03-04 17:00:00",
  "datetime": "2019-03-04:17",
  "snow": 10.45,
  "precip": 1.1,
  "temp": 1.0,
  "dewpt": 1.0,
  "max_temp": 1.5,
  "min_temp": -1.23,
  "app_max_temp": 4.0,
  "app_min_temp": -2.0,
  "rh": 95,
  "clouds": 100,
  "weather": {
    "icon": "s02n",
    "code": 601,
    "description": "Snow"
  },
  "slp": 1012.89,
  "pres": 1005.0,
  "uv": 6.5,
  "vis": 3.0,
  "pop": 75.0,
  "moon_phase": 0.87,
  "sunrise_ts": 1530331260,
  "sunset_ts": 1530331260,
  "moonrise_ts": 1530331260,
  "moonset_ts": 1530331260,
  "pod": "n",
  "wind_spd": 13.85,
  "wind_dir": 105,
  "wind_cdir": "ENE",
  "wind_cdir_full": "East-North-East"
}
