=== api-evangelist/weatherbit/json-schema/weatherbit-history-ag-obj-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/weatherbit/refs/heads/main/json-schema/weatherbit-history-ag-obj-schema.json",
  "title": "HistoryAGObj",
  "description": "HistoryAGObj schema from Weatherbit API",
  "type": "object",
  "properties": {
    "bulk_soil_density": {
      "type": "number",
      "description": "Bulk Soil Density",
      "example": 1370.0
    },
    "dlwrf_avg": {
      "type": "number",
      "description": "Average Downward Longwave Radiation Flux",
      "example": 418.656
    },
    "dlwrf_max": {
      "type": "number",
      "description": "Maximum Downward Longwave Radiation Flux",
      "example": 440.25
    },
    "dlwrf_net": {
      "type": "number",
      "description": "Net Downward Longwave Radiation Flux",
      "example": 143.0
    },
    "dswrf_avg": {
      "type": "number",
      "description": "Average Downward Shortwave Radiation Flux",
      "example": 158.848
    },
    "dswrf_max": {
      "type": "number",
      "description": "Maximum Downward Shortwave Radiation Flux",
      "example": 492.25
    },
    "dswrf_net": {
      "type": "number",
      "description": "Net Downward Shortwave Radiation Flux",
      "example": -50.832
    },
    "evapotranspiration": {
      "type": "number",
      "description": "Evapotranspiration",
      "example": 4.247
    },
    "precip": {
      "type": "number",
      "description": "Precipitation",
      "example": 18.5
    },
    "pres_avg": {
      "type": "number",
      "description": "Average Pressure",
      "example": 1011.644
    },
    "revision_status": {
      "type": "string",
      "description": "Data revision status",
      "example": "final"
    },
    "skin_temp_avg": {
      "type": "number",
      "description": "Average Skin Temperature",
      "example": 29.4
    },
    "skin_temp_max": {
      "type": "number",
      "description": "Maximum Skin Temperature",
      "example": 40.4
    },
    "skin_temp_min": {
      "type": "number",
      "description": "Minimum Skin Temperature",
      "example": 25.4
    },
    "soilm_0_10cm": {
      "type": "number",
      "description": "Soil Moisture (0-10cm depth)",
      "example": 25.697
    },
    "soilm_100_200cm": {
      "type": "number",
      "description": "Soil Moisture (100-200cm depth)",
      "example": 273.625
    },
    "soilm_10_40cm": {
      "type": "number",
      "description": "Soil Moisture (10-40cm depth)",
      "example": 72.813
    },
    "soilm_40_100cm": {
      "type": "number",
      "description": "Soil Moisture (40-100cm depth)",
      "example": 152.203
    },
    "soilt_0_10cm": {
      "type": "number",
      "description": "Soil Temperature (0-10cm depth)",
      "example": 29.5
    },
    "soilt_100_200cm": {
      "type": "number",
      "description": "Soil Temperature (100-200cm depth)",
      "example": 24.4
    },
    "soilt_10_40cm": {
      "type": "number",
      "description": "Soil Temperature (10-40cm depth)",
      "example": 29.8
    },
    "soilt_40_100cm": {
      "type": "number",
      "description": "Soil Temperature (40-100cm depth)",
      "example": 27.7
    },
    "specific_humidity": {
      "type": "number",
      "description": "Specific Humidity",
      "example": 0.014513969421387
    },
    "timestamp_local": {
      "type": "string",
      "description": "Timestamp in local time",
      "example": "2023-09-08 00:00:00"
    },
    "timestamp_utc": {
      "type": "string",
      "description": "Timestamp UTC",
      "example": "2023-09-08 00:00:00"
    },
    "temp_2m_avg": {
      "type": "number",
      "description": "Average Temperature at 2 meters",
      "example": 26.6
    },
    "v_soilm_0_10cm": {
      "type": "number",
      "description": "Volumetric Soil Moisture (0-10cm depth)",
      "example": 0.257
    },
    "v_soilm_100_200cm": {
      "type": "number",
      "description": "Volumetric Soil Moisture (100-200cm depth)",
      "example": 0.274
    },
    "v_soilm_10_40cm": {
      "type": "number",
      "description": "Volumetric Soil Moisture (10-40cm depth)",
      "example": 0.243
    },
    "v_soilm_40_100cm": {
      "type": "number",
      "description": "Volumetric Soil Moisture (40-100cm depth)",
      "example": 0.254
    },
    "valid_date": {
      "type": "string",
      "description": "Valid Date",
      "example": "2023-09-08"
    },
    "wind_10m_spd_avg": {
      "type": "number",
      "description": "Average Wind Speed at 10 meters",
      "example": 2.505
    }
  }
}

=== api-evangelist/weatherbit/examples/weatherbit-history-ag-obj-example.json
{
  "bulk_soil_density": 1370.0,
  "dlwrf_avg": 418.656,
  "dlwrf_max": 440.25,
  "dlwrf_net": 143.0,
  "dswrf_avg": 158.848,
  "dswrf_max": 492.25,
  "dswrf_net": -50.832,
  "evapotranspiration": 4.247,
  "precip": 18.5,
  "pres_avg": 1011.644,
  "revision_status": "final",
  "skin_temp_avg": 29.4,
  "skin_temp_max": 40.4,
  "skin_temp_min": 25.4,
  "soilm_0_10cm": 25.697,
  "soilm_100_200cm": 273.625,
  "soilm_10_40cm": 72.813,
  "soilm_40_100cm": 152.203,
  "soilt_0_10cm": 29.5,
  "soilt_100_200cm": 24.4,
  "soilt_10_40cm": 29.8,
  "soilt_40_100cm": 27.7,
  "specific_humidity": 0.014513969421387,
  "timestamp_local": "2023-09-08 00:00:00",
  "timestamp_utc": "2023-09-08 00:00:00",
  "temp_2m_avg": 26.6,
  "v_soilm_0_10cm": 0.257,
  "v_soilm_100_200cm": 0.274,
  "v_soilm_10_40cm": 0.243,
  "v_soilm_40_100cm": 0.254,
  "valid_date": "2023-09-08",
  "wind_10m_spd_avg": 2.505
}
