=== api-evangelist/weatherbit/json-schema/weatherbit-energy-obs-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/weatherbit/refs/heads/main/json-schema/weatherbit-energy-obs-schema.json",
  "title": "EnergyObs",
  "description": "EnergyObs schema from Weatherbit API",
  "type": "object",
  "properties": {
    "city_name": {
      "type": "string",
      "description": "City name (closest)",
      "example": "Raleigh"
    },
    "state_code": {
      "type": "string",
      "description": "State abbreviation",
      "example": "NC"
    },
    "country_code": {
      "type": "string",
      "description": "Country abbreviation",
      "example": "US"
    },
    "timezone": {
      "type": "string",
      "description": "Local IANA time zone",
      "example": "America/New_York"
    },
    "lat": {
      "type": "number",
      "description": "Latitude",
      "example": 38.0
    },
    "lon": {
      "type": "number",
      "description": "Longitude",
      "example": -78.25
    },
    "station_id": {
      "type": "string",
      "description": "Nearest Station ID [DEPRECATED]",
      "example": "12345-999999"
    },
    "sources": {
      "type": "array",
      "description": "List of data sources used in response",
      "items": {
        "type": "string",
        "example": "12345-89083"
      }
    },
    "cdd": {
      "type": "number",
      "description": "Cooling degree days",
      "example": 10.0
    },
    "hdd": {
      "type": "number",
      "description": "Heating degree days",
      "example": 120.0
    },
    "rh": {
      "type": "integer",
      "description": "Average Relative humidity (%)",
      "example": 75
    },
    "dewpt": {
      "type": "number",
      "description": "Average dew point temperature - Default (C)",
      "example": 12.0
    },
    "wind_dir": {
      "type": "integer",
      "description": "Average wind direction (Degrees)",
      "example": 125
    },
    "wind_spd": {
      "type": "number",
      "description": "Average wind speed - Default (m/s)",
      "example": 5.85
    },
    "temp": {
      "type": "number",
      "description": "Average temperature - Default (C)",
      "example": 13.85
    },
    "clouds": {
      "type": "integer",
      "description": "Average cloud cover (%)",
      "example": 42
    },
    "t_ghi": {
      "type": "number",
      "description": "Total global horizontal solar irradiance (W/m^2)",
      "example": 3000.0
    },
    "t_dhi": {
      "type": "number",
      "description": "Total diffuse horizontal solar irradiance (W/m^2)",
      "example": 450.0
    },
    "t_dni": {
      "type": "number",
      "description": "Total direct normal solar irradiance (W/m^2)",
      "example": 1200.0
    },
    "sun_hours": {
      "type": "number",
      "description": "Average number of daily sun hours - # hours where Solar GHI > 1000 W/m^2",
      "example": 4.5
    },
    "precip": {
      "type": "number",
      "description": "Total precipitation in period - Default (mm)",
      "example": 2.0
    },
    "snow": {
      "type": "number",
      "description": "Total snowfall in period - Default (mm)",
      "example": 10.0
    }
  }
}

=== api-evangelist/weatherbit/examples/weatherbit-energy-obs-example.json
{
  "city_name": "Raleigh",
  "state_code": "NC",
  "country_code": "US",
  "timezone": "America/New_York",
  "lat": 38.0,
  "lon": -78.25,
  "station_id": "12345-999999",
  "sources": [
    "12345-89083"
  ],
  "cdd": 10.0,
  "hdd": 120.0,
  "rh": 75,
  "dewpt": 12.0,
  "wind_dir": 125,
  "wind_spd": 5.85,
  "temp": 13.85,
  "clouds": 42,
  "t_ghi": 3000.0,
  "t_dhi": 450.0,
  "t_dni": 1200.0,
  "sun_hours": 4.5,
  "precip": 2.0,
  "snow": 10.0
}
